### ISSUE TITLE
启动丢失msvcr100.dll

### ISSUE THREAD

**Issue by zhuoyikang** [sniperHW/Survive#3]
已安装c++ 2010 运行时;
msvcr100.dll 已经存在于Systen32/下面

还是报错，

**Comment by sniperHW** [comment]
你说客户端是吧，所有运行时哭在runtime/win32下面都应该全的啊

**Comment by zhuoyikang** [comment]
你是用的什么系统？ 64还是32位的？

**Comment by sniperHW** [comment]
编译机器是64位的

**Comment by zhuoyikang** [comment]
你是XP还是WIN 7 还是？

**Comment by sniperHW** [comment]
win7

**Comment by zhuoyikang** [comment]
是不是要安装一点其他的东西才行，你编译环境都有些什么东西呢？

**Comment by sniperHW** [comment]
你把你的错误贴出来吧

**Comment by zhuoyikang** [comment]
![1 pic](https://cloud.githubusercontent.com/assets/2211585/10135227/94377f1c-661e-11e5-87e9-ccb92f689ff3.jpg)

**Comment by zhuoyikang** [comment]
这个提示怪怪的，我看runtime下面各种dll都有，关键是我安装了MSVCR100也解决不了，

**Comment by sniperHW** [comment]
把文件拷贝到运行目录下试试

**Comment by zhuoyikang** [comment]
我觉得是你链接的时候错了把，虽然你把msvcr120.dll等拷贝到运行目录，但是链接的却是msvcr100.
另外拷贝msvcr100到目录也会报其他的错误。

要不然你直接把你的编译工程共享出来。

**Comment by sniperHW** [comment]
http://code.taobao.org/svn/surviveclient/ 到这里去取编译c++部分就行了,lua部分不是最新的

**Comment by zhuoyikang** [comment]
编译了一个mac版上机了Iphone。

玩了一下；
pvp大部分功能都没实现吧，匹配到的都是机器人。

**Comment by zhuoyikang** [comment]
摇杆也不能用。
