### ISSUE TITLE
关于Survive的运行

### ISSUE THREAD

**Issue by wagulu** [sniperHW/Survive#4]
运行groupserver后， 在运行gateserver.lua和gameserver.lua 的 “连接groupserver并完成登陆” 这一步会停止运行：login group failed:remote connection lose
groupserver这边会有一条打印：fcntl set  FD_CLOEXEC error
请问这个问题要怎么解决呢？

**Comment by sniperHW** [comment]
操作系统版本是什么

**Comment by wagulu** [comment]
Linux version 3.4.0-Microsoft (Microsoft@Microsoft.com) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Wed Dec 31 14:42:53 PST 2014
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04

win10带的

**Comment by sniperHW** [comment]
这我就不知道了，用虚拟机装一个，win10下的没试过

**Comment by wagulu** [comment]
的确，用虚拟机可以了

**Comment by wagulu** [comment]
是因为KendyNet有个bug，我提交到distri.lua里面了

**Comment by wagulu** [comment]
是因为KendyNet有个bug，我提交到distri.lua里面了

**Comment by sniperHW** [comment]
提交哪，没看到


发自我的 iPhone

**Comment by wagulu** [comment]
在你的distri.lua里面

**Comment by sniperHW** [comment]
pull 你的 commit 否则我看不到

**Comment by SpringStudent** [comment]
客户端下载不到源码
